---

apiVersion: v1
kind: Service
metadata:
  name: finance-hub
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "600"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-west-1:797036517683:certificate/ff6b8f38-e500-48ba-845e-2ba3d7238213"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  type: LoadBalancer
  selector:
    app: finance-hub
  ports:
  - name: finance-hub
    port: 443
    targetPort: finance-hub

---
apiVersion: v1
kind: Service
metadata:
  name: finance-hub-service
spec:
  type: ClusterIP
  selector:
    app: finance-hub
  ports:
    - port: 80
      targetPort: finance-hub
      protocol: TCP
      name: http
